const fs = require('fs').promises;
const path = require('path');

const IMAGE_DIR = path.join(process.cwd(), 'images');
const OUT_FILE = path.join(process.cwd(), 'js', 'seed-images.js');

const mimeMap = {
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.png': 'image/png',
  '.gif': 'image/gif',
  '.webp': 'image/webp',
  '.svg': 'image/svg+xml'
};

async function walk(dir) {
  let results = [];
  const list = await fs.readdir(dir, { withFileTypes: true });
  for (const entry of list) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results = results.concat(await walk(full));
    } else if (entry.isFile()) {
      results.push(full);
    }
  }
  return results;
}

async function main() {
  try {
    await fs.mkdir(path.dirname(OUT_FILE), { recursive: true });
    const files = await walk(IMAGE_DIR);
    const mapping = {};

    for (const file of files) {
      const ext = path.extname(file).toLowerCase();
      const mime = mimeMap[ext] || 'application/octet-stream';
      const data = await fs.readFile(file);
      const b64 = data.toString('base64');
      const rel = path.relative(process.cwd(), file).split(path.sep).join('/');
      mapping[rel] = 'data:' + mime + ';base64,' + b64;
      console.log('Encoded', rel);
    }

    const header = '// This file is autogenerated by scripts/encode-images.js - do not edit\n';
    const body = 'window.SEED_IMAGES = ' + JSON.stringify(mapping, null, 2) + ';\n';
    const out = header + body;

    await fs.writeFile(OUT_FILE, out, 'utf8');
    console.log('\nWrote', OUT_FILE);
    console.log('Total images encoded:', Object.keys(mapping).length);
  } catch (err) {
    console.error('Error encoding images:', err);
    process.exit(1);
  }
}

main();
